(source gnu)
(source melpa)

(package "sql-reformat" "0.0.1" "Reformat SQL code.")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "ert-runner")
 (depends-on "rdp"))